package com.cemedo.data;
// Generated 1 juin 2022 � 14:01:29 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Adresse generated by hbm2java
 */
@Entity
@Table(name = "adresse", catalog = "heroku_88ae11bd39df693")
public class Adresse implements java.io.Serializable {

	private Integer idAdresse;
	private Patient patient;
	private String libelleAdresse;
	private Double latitudeAdresse;
	private Double longitudeAdresse;

	public Adresse() {
	}

	public Adresse(Patient patient, String libelleAdresse, Double latitudeAdresse, Double longitudeAdresse) {
		this.patient = patient;
		this.libelleAdresse = libelleAdresse;
		this.latitudeAdresse = latitudeAdresse;
		this.longitudeAdresse = longitudeAdresse;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)

	@Column(name = "id_Adresse", unique = true, nullable = false)
	public Integer getIdAdresse() {
		return this.idAdresse;
	}

	public void setIdAdresse(Integer idAdresse) {
		this.idAdresse = idAdresse;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Patients_id_Patients")
	public Patient getPatient() {
		return this.patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	@Column(name = "libelle_Adresse", length = 45)
	public String getLibelleAdresse() {
		return this.libelleAdresse;
	}

	public void setLibelleAdresse(String libelleAdresse) {
		this.libelleAdresse = libelleAdresse;
	}

	@Column(name = "latitude_Adresse", precision = 22, scale = 0)
	public Double getLatitudeAdresse() {
		return this.latitudeAdresse;
	}

	public void setLatitudeAdresse(Double latitudeAdresse) {
		this.latitudeAdresse = latitudeAdresse;
	}

	@Column(name = "longitude_Adresse", precision = 22, scale = 0)
	public Double getLongitudeAdresse() {
		return this.longitudeAdresse;
	}

	public void setLongitudeAdresse(Double longitudeAdresse) {
		this.longitudeAdresse = longitudeAdresse;
	}

}
