package  com.cemedo.data;
// Generated 1 juin 2022 � 14:01:29 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Antecedant generated by hbm2java
 */
@Entity
@Table(name = "antecedant", catalog = "heroku_88ae11bd39df693")
public class Antecedant implements java.io.Serializable {

	private Integer idAntecedants;
	private Patient patient;
	private String keyAntecedants;
	private String libelleAntecedants;
	private Integer valueAntecedants;

	public Antecedant() {
	}

	public Antecedant(Patient patient, String keyAntecedants, String libelleAntecedants, Integer valueAntecedants) {
		this.patient = patient;
		this.keyAntecedants = keyAntecedants;
		this.libelleAntecedants = libelleAntecedants;
		this.valueAntecedants = valueAntecedants;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)

	@Column(name = "id_antecedants", unique = true, nullable = false)
	public Integer getIdAntecedants() {
		return this.idAntecedants;
	}

	public void setIdAntecedants(Integer idAntecedants) {
		this.idAntecedants = idAntecedants;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Patients_id_Patients")
	public Patient getPatient() {
		return this.patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	@Column(name = "key_antecedants", length = 45)
	public String getKeyAntecedants() {
		return this.keyAntecedants;
	}

	public void setKeyAntecedants(String keyAntecedants) {
		this.keyAntecedants = keyAntecedants;
	}

	@Column(name = "libelle_antecedants", length = 45)
	public String getLibelleAntecedants() {
		return this.libelleAntecedants;
	}

	public void setLibelleAntecedants(String libelleAntecedants) {
		this.libelleAntecedants = libelleAntecedants;
	}

	@Column(name = "value_antecedants")
	public Integer getValueAntecedants() {
		return this.valueAntecedants;
	}

	public void setValueAntecedants(Integer valueAntecedants) {
		this.valueAntecedants = valueAntecedants;
	}

}
