package  com.cemedo.data;
// Generated 1 juin 2022 � 14:01:29 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Appl generated by hbm2java
 */
@Entity
@Table(name = "appl", catalog = "heroku_88ae11bd39df693")
public class Appl implements java.io.Serializable {

	private Integer idAppels;
	private Medecin medecin;
	private Patient patient;
	private Reception reception;
	private String typeAppels;
	private Date dateAppels;
	private String coutAppels;
	private String dureeAppels;

	public Appl() {
	}

	public Appl(Patient patient, String typeAppels, Date dateAppels) {
		this.patient = patient;
		this.typeAppels = typeAppels;
		this.dateAppels = dateAppels;
	}

	public Appl(Medecin medecin, Patient patient, Reception reception, String typeAppels, Date dateAppels,
			String coutAppels, String dureeAppels) {
		this.medecin = medecin;
		this.patient = patient;
		this.reception = reception;
		this.typeAppels = typeAppels;
		this.dateAppels = dateAppels;
		this.coutAppels = coutAppels;
		this.dureeAppels = dureeAppels;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_appels", unique = true, nullable = false)
	public Integer getIdAppels() {
		return this.idAppels;
	}

	public void setIdAppels(Integer idAppels) {
		this.idAppels = idAppels;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Medecins_id_Medecins")
	public Medecin getMedecin() {
		return this.medecin;
	}

	public void setMedecin(Medecin medecin) {
		this.medecin = medecin;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Patients_id_Patients", nullable = false)
	public Patient getPatient() {
		return this.patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Receptions_id_reception")
	public Reception getReception() {
		return this.reception;
	}

	public void setReception(Reception reception) {
		this.reception = reception;
	}

	@Column(name = "type_appels", nullable = false, length = 45)
	public String getTypeAppels() {
		return this.typeAppels;
	}

	public void setTypeAppels(String typeAppels) {
		this.typeAppels = typeAppels;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_appels", nullable = false, length = 10)
	public Date getDateAppels() {
		return this.dateAppels;
	}

	public void setDateAppels(Date dateAppels) {
		this.dateAppels = dateAppels;
	}

	@Column(name = "cout_appels", length = 45)
	public String getCoutAppels() {
		return this.coutAppels;
	}

	public void setCoutAppels(String coutAppels) {
		this.coutAppels = coutAppels;
	}

	@Column(name = "duree_appels", length = 45)
	public String getDureeAppels() {
		return this.dureeAppels;
	}

	public void setDureeAppels(String dureeAppels) {
		this.dureeAppels = dureeAppels;
	}

}
