package  com.cemedo.data;
// Generated 1 juin 2022 � 14:01:29 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Assurance generated by hbm2java
 */
@Entity
@Table(name = "assurance", catalog = "heroku_88ae11bd39df693")
public class Assurance implements java.io.Serializable {

	private Integer idAssurance;
	private String nomAssurance;
	private String emailAssurance;
	private int telephoneAssurance;
	private String villeAssurance;
	private String nomCorrespondant;
	private String emailCorrespondant;
	private int telephoneCorrespondant;
	private Set<Patient> patients = new HashSet<Patient>(0);

	public Assurance() {
	}

	public Assurance(String nomAssurance, String emailAssurance, int telephoneAssurance, String villeAssurance,
			String nomCorrespondant, String emailCorrespondant, int telephoneCorrespondant) {
		this.nomAssurance = nomAssurance;
		this.emailAssurance = emailAssurance;
		this.telephoneAssurance = telephoneAssurance;
		this.villeAssurance = villeAssurance;
		this.nomCorrespondant = nomCorrespondant;
		this.emailCorrespondant = emailCorrespondant;
		this.telephoneCorrespondant = telephoneCorrespondant;
	}

	public Assurance(String nomAssurance, String emailAssurance, int telephoneAssurance, String villeAssurance,
			String nomCorrespondant, String emailCorrespondant, int telephoneCorrespondant, Set<Patient> patients) {
		this.nomAssurance = nomAssurance;
		this.emailAssurance = emailAssurance;
		this.telephoneAssurance = telephoneAssurance;
		this.villeAssurance = villeAssurance;
		this.nomCorrespondant = nomCorrespondant;
		this.emailCorrespondant = emailCorrespondant;
		this.telephoneCorrespondant = telephoneCorrespondant;
		this.patients = patients;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_Assurance", unique = true, nullable = false)
	public Integer getIdAssurance() {
		return this.idAssurance;
	}

	public void setIdAssurance(Integer idAssurance) {
		this.idAssurance = idAssurance;
	}

	@Column(name = "nom_assurance", nullable = false, length = 45)
	public String getNomAssurance() {
		return this.nomAssurance;
	}

	public void setNomAssurance(String nomAssurance) {
		this.nomAssurance = nomAssurance;
	}

	@Column(name = "email_assurance", nullable = false, length = 45)
	public String getEmailAssurance() {
		return this.emailAssurance;
	}

	public void setEmailAssurance(String emailAssurance) {
		this.emailAssurance = emailAssurance;
	}

	@Column(name = "telephone_assurance", nullable = false)
	public int getTelephoneAssurance() {
		return this.telephoneAssurance;
	}

	public void setTelephoneAssurance(int telephoneAssurance) {
		this.telephoneAssurance = telephoneAssurance;
	}

	@Column(name = "ville_assurance", nullable = false, length = 45)
	public String getVilleAssurance() {
		return this.villeAssurance;
	}

	public void setVilleAssurance(String villeAssurance) {
		this.villeAssurance = villeAssurance;
	}

	@Column(name = "nom_correspondant", nullable = false, length = 45)
	public String getNomCorrespondant() {
		return this.nomCorrespondant;
	}

	public void setNomCorrespondant(String nomCorrespondant) {
		this.nomCorrespondant = nomCorrespondant;
	}

	@Column(name = "email_correspondant", nullable = false, length = 45)
	public String getEmailCorrespondant() {
		return this.emailCorrespondant;
	}

	public void setEmailCorrespondant(String emailCorrespondant) {
		this.emailCorrespondant = emailCorrespondant;
	}

	@Column(name = "telephone_correspondant", nullable = false)
	public int getTelephoneCorrespondant() {
		return this.telephoneCorrespondant;
	}

	public void setTelephoneCorrespondant(int telephoneCorrespondant) {
		this.telephoneCorrespondant = telephoneCorrespondant;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "assurance")
	public Set<Patient> getPatients() {
		return this.patients;
	}

	public void setPatients(Set<Patient> patients) {
		this.patients = patients;
	}

}
