package  com.cemedo.data;
// Generated 1 juin 2022 � 14:01:29 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Chat generated by hbm2java
 */
@Entity
@Table(name = "chat", catalog = "heroku_88ae11bd39df693")
public class Chat implements java.io.Serializable {

	private Integer idChats;
	private Medecin medecin;
	private Patient patient;
	private Reception reception;
	private Date dateChats;
	private String coutChats;
	private String dureeChats;
	private String descriptionChats;

	public Chat() {
	}

	public Chat(Patient patient, Date dateChats) {
		this.patient = patient;
		this.dateChats = dateChats;
	}

	public Chat(Medecin medecin, Patient patient, Reception reception, Date dateChats, String coutChats,
			String dureeChats, String descriptionChats) {
		this.medecin = medecin;
		this.patient = patient;
		this.reception = reception;
		this.dateChats = dateChats;
		this.coutChats = coutChats;
		this.dureeChats = dureeChats;
		this.descriptionChats = descriptionChats;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_chats", unique = true, nullable = false)
	public Integer getIdChats() {
		return this.idChats;
	}

	public void setIdChats(Integer idChats) {
		this.idChats = idChats;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Medecins_id_Medecins")
	public Medecin getMedecin() {
		return this.medecin;
	}

	public void setMedecin(Medecin medecin) {
		this.medecin = medecin;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Patients_id_Patients", nullable = false)
	public Patient getPatient() {
		return this.patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Receptions_id_reception")
	public Reception getReception() {
		return this.reception;
	}

	public void setReception(Reception reception) {
		this.reception = reception;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_chats", nullable = false, length = 10)
	public Date getDateChats() {
		return this.dateChats;
	}

	public void setDateChats(Date dateChats) {
		this.dateChats = dateChats;
	}

	@Column(name = "cout_chats", length = 45)
	public String getCoutChats() {
		return this.coutChats;
	}

	public void setCoutChats(String coutChats) {
		this.coutChats = coutChats;
	}

	@Column(name = "duree_chats", length = 45)
	public String getDureeChats() {
		return this.dureeChats;
	}

	public void setDureeChats(String dureeChats) {
		this.dureeChats = dureeChats;
	}

	@Column(name = "description_chats", length = 200)
	public String getDescriptionChats() {
		return this.descriptionChats;
	}

	public void setDescriptionChats(String descriptionChats) {
		this.descriptionChats = descriptionChats;
	}

}
