package  com.cemedo.data;
// Generated 1 juin 2022 � 14:01:29 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DossierId generated by hbm2java
 */
@Embeddable
public class DossierId implements java.io.Serializable {

	private int idDossier;
	private int patientsIdPatients;

	public DossierId() {
	}

	public DossierId(int idDossier, int patientsIdPatients) {
		this.idDossier = idDossier;
		this.patientsIdPatients = patientsIdPatients;
	}

	@Column(name = "id_dossier", nullable = false)
	public int getIdDossier() {
		return this.idDossier;
	}

	public void setIdDossier(int idDossier) {
		this.idDossier = idDossier;
	}

	@Column(name = "Patients_id_Patients", nullable = false)
	public int getPatientsIdPatients() {
		return this.patientsIdPatients;
	}

	public void setPatientsIdPatients(int patientsIdPatients) {
		this.patientsIdPatients = patientsIdPatients;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DossierId))
			return false;
		DossierId castOther = (DossierId) other;

		return (this.getIdDossier() == castOther.getIdDossier())
				&& (this.getPatientsIdPatients() == castOther.getPatientsIdPatients());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdDossier();
		result = 37 * result + this.getPatientsIdPatients();
		return result;
	}

}
