package  com.cemedo.data;
// Generated 1 juin 2022 � 14:01:29 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Dossier generated by hbm2java
 */
@Entity
@Table(name = "dossier", catalog = "heroku_88ae11bd39df693")
public class Dossier implements java.io.Serializable {

	private int idDossier;
	private Patient patient;
	private String libelleDossier;
	private String typeDossier;
	private String descriptionDossier;
	private Set<Medecin> medecins = new HashSet<Medecin>(0);

	public Dossier() {
	}

	public Dossier(int id, Patient patient, String libelleDossier, String typeDossier,
			String descriptionDossier) {
		this.setIdDossier(id);
		this.patient = patient;
		this.libelleDossier = libelleDossier;
		this.typeDossier = typeDossier;
		this.descriptionDossier = descriptionDossier;
	}

	public Dossier(int id, Patient patient, String libelleDossier, String typeDossier, String descriptionDossier,
			Set<Medecin> medecins) {
		this.setIdDossier(id);
		this.patient = patient;
		this.libelleDossier = libelleDossier;
		this.typeDossier = typeDossier;
		this.descriptionDossier = descriptionDossier;
		this.medecins = medecins;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_dossier", unique = true, nullable = false)
	public int getIdDossier() {
		return idDossier;
	}

	public void setIdDossier(int idDossier) {
		this.idDossier = idDossier;
	}
	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Patients_id_Patients", nullable = false, insertable = false, updatable = false)
	public Patient getPatient() {
		return this.patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	@Column(name = "libelle_dossier", nullable = false, length = 45)
	public String getLibelleDossier() {
		return this.libelleDossier;
	}

	public void setLibelleDossier(String libelleDossier) {
		this.libelleDossier = libelleDossier;
	}

	@Column(name = "type_dossier", nullable = false, length = 45)
	public String getTypeDossier() {
		return this.typeDossier;
	}

	public void setTypeDossier(String typeDossier) {
		this.typeDossier = typeDossier;
	}

	@Column(name = "description_dossier", nullable = false, length = 45)
	public String getDescriptionDossier() {
		return this.descriptionDossier;
	}

	public void setDescriptionDossier(String descriptionDossier) {
		this.descriptionDossier = descriptionDossier;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "dossiers_has_medecins", catalog = "heroku_88ae11bd39df693", joinColumns = {
			@JoinColumn(name = "Dossiers_id_dossier", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "Medecins_id_Medecins", nullable = false, updatable = false) })
	public Set<Medecin> getMedecins() {
		return this.medecins;
	}

	public void setMedecins(Set<Medecin> medecins) {
		this.medecins = medecins;
	}


}
