package  com.cemedo.data;
// Generated 1 juin 2022 � 14:01:29 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Examen generated by hbm2java
 */
@Entity
@Table(name = "examen", catalog = "heroku_88ae11bd39df693")
public class Examen implements java.io.Serializable {

	private Integer idExamen;
	private Infirmier infirmier;
	private Medecin medecin;
	private Patient patient;
	private String monExamen;
	private String descriptionExamen;
	private String resultatExamen;
	private String libelleExamens;
	private Set<Ordonnance> ordonnances = new HashSet<Ordonnance>(0);

	public Examen() {
	}

	public Examen(Medecin medecin, Patient patient, String monExamen, String descriptionExamen) {
		this.medecin = medecin;
		this.patient = patient;
		this.monExamen = monExamen;
		this.descriptionExamen = descriptionExamen;
	}

	public Examen(Infirmier infirmier, Medecin medecin, Patient patient, String monExamen, String descriptionExamen,
			String resultatExamen, String libelleExamens, Set<Ordonnance> ordonnances) {
		this.infirmier = infirmier;
		this.medecin = medecin;
		this.patient = patient;
		this.monExamen = monExamen;
		this.descriptionExamen = descriptionExamen;
		this.resultatExamen = resultatExamen;
		this.libelleExamens = libelleExamens;
		this.ordonnances = ordonnances;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_examen", unique = true, nullable = false)
	public Integer getIdExamen() {
		return this.idExamen;
	}

	public void setIdExamen(Integer idExamen) {
		this.idExamen = idExamen;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Infirmiers_id_infirmier")
	public Infirmier getInfirmier() {
		return this.infirmier;
	}

	public void setInfirmier(Infirmier infirmier) {
		this.infirmier = infirmier;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Medecins_id_Medecins", nullable = false)
	public Medecin getMedecin() {
		return this.medecin;
	}

	public void setMedecin(Medecin medecin) {
		this.medecin = medecin;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Patients_id_Patients", nullable = false)
	public Patient getPatient() {
		return this.patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	@Column(name = "mon_examen", nullable = false, length = 45)
	public String getMonExamen() {
		return this.monExamen;
	}

	public void setMonExamen(String monExamen) {
		this.monExamen = monExamen;
	}

	@Column(name = "description_examen", nullable = false, length = 45)
	public String getDescriptionExamen() {
		return this.descriptionExamen;
	}

	public void setDescriptionExamen(String descriptionExamen) {
		this.descriptionExamen = descriptionExamen;
	}

	@Column(name = "resultat_Examen", length = 200)
	public String getResultatExamen() {
		return this.resultatExamen;
	}

	public void setResultatExamen(String resultatExamen) {
		this.resultatExamen = resultatExamen;
	}

	@Column(name = "libelle_Examens", length = 45)
	public String getLibelleExamens() {
		return this.libelleExamens;
	}

	public void setLibelleExamens(String libelleExamens) {
		this.libelleExamens = libelleExamens;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "ordonnances_has_examens", catalog = "heroku_88ae11bd39df693", joinColumns = {
			@JoinColumn(name = "Examens_id_examen", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "Ordonnances_id_ordonnance", nullable = false, updatable = false) })
	public Set<Ordonnance> getOrdonnances() {
		return this.ordonnances;
	}

	public void setOrdonnances(Set<Ordonnance> ordonnances) {
		this.ordonnances = ordonnances;
	}

}
