package  com.cemedo.data;
// Generated 1 juin 2022 � 14:01:29 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FacturepatientId generated by hbm2java
 */
@Embeddable
public class FacturepatientId implements java.io.Serializable {

	private int numeroFacture;
	private int patientsIdPatients;
	private int medecinsIdMedecins;

	public FacturepatientId() {
	}

	public FacturepatientId(int numeroFacture, int patientsIdPatients, int medecinsIdMedecins) {
		this.numeroFacture = numeroFacture;
		this.patientsIdPatients = patientsIdPatients;
		this.medecinsIdMedecins = medecinsIdMedecins;
	}

	@Column(name = "numero_Facture", nullable = false)
	public int getNumeroFacture() {
		return this.numeroFacture;
	}

	public void setNumeroFacture(int numeroFacture) {
		this.numeroFacture = numeroFacture;
	}

	@Column(name = "Patients_id_Patients", nullable = false)
	public int getPatientsIdPatients() {
		return this.patientsIdPatients;
	}

	public void setPatientsIdPatients(int patientsIdPatients) {
		this.patientsIdPatients = patientsIdPatients;
	}

	@Column(name = "Medecins_id_Medecins", nullable = false)
	public int getMedecinsIdMedecins() {
		return this.medecinsIdMedecins;
	}

	public void setMedecinsIdMedecins(int medecinsIdMedecins) {
		this.medecinsIdMedecins = medecinsIdMedecins;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FacturepatientId))
			return false;
		FacturepatientId castOther = (FacturepatientId) other;

		return (this.getNumeroFacture() == castOther.getNumeroFacture())
				&& (this.getPatientsIdPatients() == castOther.getPatientsIdPatients())
				&& (this.getMedecinsIdMedecins() == castOther.getMedecinsIdMedecins());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNumeroFacture();
		result = 37 * result + this.getPatientsIdPatients();
		result = 37 * result + this.getMedecinsIdMedecins();
		return result;
	}

}
