package  com.cemedo.data;
// Generated 1 juin 2022 � 14:01:29 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Famille generated by hbm2java
 */
@Entity
@Table(name = "famille", catalog = "heroku_88ae11bd39df693")
public class Famille implements java.io.Serializable {

	private Integer idFamille;
	private Patient patient;
	private String nomFamille;
	private String nomMembre;
	private String prenomMembre;
	private Date dateNaissanceMembre;
	private String genreMembre;

	public Famille() {
	}

	public Famille(String nomFamille, String nomMembre, String prenomMembre, Date dateNaissanceMembre,
			String genreMembre) {
		this.nomFamille = nomFamille;
		this.nomMembre = nomMembre;
		this.prenomMembre = prenomMembre;
		this.dateNaissanceMembre = dateNaissanceMembre;
		this.genreMembre = genreMembre;
	}

	public Famille(Patient patient, String nomFamille, String nomMembre, String prenomMembre, Date dateNaissanceMembre,
			String genreMembre) {
		this.patient = patient;
		this.nomFamille = nomFamille;
		this.nomMembre = nomMembre;
		this.prenomMembre = prenomMembre;
		this.dateNaissanceMembre = dateNaissanceMembre;
		this.genreMembre = genreMembre;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)

	@Column(name = "id_Famille", unique = true, nullable = false)
	public Integer getIdFamille() {
		return this.idFamille;
	}

	public void setIdFamille(Integer idFamille) {
		this.idFamille = idFamille;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Patients_id_Patients")
	public Patient getPatient() {
		return this.patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	@Column(name = "nom_famille", nullable = false, length = 45)
	public String getNomFamille() {
		return this.nomFamille;
	}

	public void setNomFamille(String nomFamille) {
		this.nomFamille = nomFamille;
	}

	@Column(name = "nom_membre", nullable = false, length = 45)
	public String getNomMembre() {
		return this.nomMembre;
	}

	public void setNomMembre(String nomMembre) {
		this.nomMembre = nomMembre;
	}

	@Column(name = "prenom_membre", nullable = false, length = 45)
	public String getPrenomMembre() {
		return this.prenomMembre;
	}

	public void setPrenomMembre(String prenomMembre) {
		this.prenomMembre = prenomMembre;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_naissance_membre", nullable = false, length = 26)
	public Date getDateNaissanceMembre() {
		return this.dateNaissanceMembre;
	}

	public void setDateNaissanceMembre(Date dateNaissanceMembre) {
		this.dateNaissanceMembre = dateNaissanceMembre;
	}

	@Column(name = "genre_membre", nullable = false, length = 45)
	public String getGenreMembre() {
		return this.genreMembre;
	}

	public void setGenreMembre(String genreMembre) {
		this.genreMembre = genreMembre;
	}

}
