package  com.cemedo.data;
// Generated 1 juin 2022 � 14:01:29 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Infirmier generated by hbm2java
 */
@Entity
@Table(name = "infirmier", catalog = "heroku_88ae11bd39df693")
public class Infirmier implements java.io.Serializable {

	private Integer idInfirmier;
	private String nomInfirmier;
	private String prenomInfirmier;
	private String genreInfirmier;
	private String residenceInfirmier;
	private String emailInfirmier;
	private int telephoneInfirmier;
	private String passwordInfirmier;
	private int numeroCniInfirmier;
	private String photoInfirmier;
	private Double salaireInfirmier;
	private Set<Examen> examens = new HashSet<Examen>(0);

	public Infirmier() {
	}

	public Infirmier(String nomInfirmier, String prenomInfirmier, String genreInfirmier, String residenceInfirmier,
			String emailInfirmier, int telephoneInfirmier, String passwordInfirmier, int numeroCniInfirmier) {
		this.nomInfirmier = nomInfirmier;
		this.prenomInfirmier = prenomInfirmier;
		this.genreInfirmier = genreInfirmier;
		this.residenceInfirmier = residenceInfirmier;
		this.emailInfirmier = emailInfirmier;
		this.telephoneInfirmier = telephoneInfirmier;
		this.passwordInfirmier = passwordInfirmier;
		this.numeroCniInfirmier = numeroCniInfirmier;
	}

	public Infirmier(String nomInfirmier, String prenomInfirmier, String genreInfirmier, String residenceInfirmier,
			String emailInfirmier, int telephoneInfirmier, String passwordInfirmier, int numeroCniInfirmier,
			String photoInfirmier, Double salaireInfirmier, Set<Examen> examens) {
		this.nomInfirmier = nomInfirmier;
		this.prenomInfirmier = prenomInfirmier;
		this.genreInfirmier = genreInfirmier;
		this.residenceInfirmier = residenceInfirmier;
		this.emailInfirmier = emailInfirmier;
		this.telephoneInfirmier = telephoneInfirmier;
		this.passwordInfirmier = passwordInfirmier;
		this.numeroCniInfirmier = numeroCniInfirmier;
		this.photoInfirmier = photoInfirmier;
		this.salaireInfirmier = salaireInfirmier;
		this.examens = examens;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_infirmier", unique = true, nullable = false)
	public Integer getIdInfirmier() {
		return this.idInfirmier;
	}

	public void setIdInfirmier(Integer idInfirmier) {
		this.idInfirmier = idInfirmier;
	}

	@Column(name = "nom_infirmier", nullable = false, length = 45)
	public String getNomInfirmier() {
		return this.nomInfirmier;
	}

	public void setNomInfirmier(String nomInfirmier) {
		this.nomInfirmier = nomInfirmier;
	}

	@Column(name = "prenom_infirmier", nullable = false, length = 45)
	public String getPrenomInfirmier() {
		return this.prenomInfirmier;
	}

	public void setPrenomInfirmier(String prenomInfirmier) {
		this.prenomInfirmier = prenomInfirmier;
	}

	@Column(name = "genre_infirmier", nullable = false, length = 45)
	public String getGenreInfirmier() {
		return this.genreInfirmier;
	}

	public void setGenreInfirmier(String genreInfirmier) {
		this.genreInfirmier = genreInfirmier;
	}

	@Column(name = "residence_infirmier", nullable = false, length = 45)
	public String getResidenceInfirmier() {
		return this.residenceInfirmier;
	}

	public void setResidenceInfirmier(String residenceInfirmier) {
		this.residenceInfirmier = residenceInfirmier;
	}

	@Column(name = "email_infirmier", nullable = false, length = 45)
	public String getEmailInfirmier() {
		return this.emailInfirmier;
	}

	public void setEmailInfirmier(String emailInfirmier) {
		this.emailInfirmier = emailInfirmier;
	}

	@Column(name = "telephone_infirmier", nullable = false)
	public int getTelephoneInfirmier() {
		return this.telephoneInfirmier;
	}

	public void setTelephoneInfirmier(int telephoneInfirmier) {
		this.telephoneInfirmier = telephoneInfirmier;
	}

	@Column(name = "password_infirmier", nullable = false, length = 45)
	public String getPasswordInfirmier() {
		return this.passwordInfirmier;
	}

	public void setPasswordInfirmier(String passwordInfirmier) {
		this.passwordInfirmier = passwordInfirmier;
	}

	@Column(name = "numero_CNI_infirmier", nullable = false)
	public int getNumeroCniInfirmier() {
		return this.numeroCniInfirmier;
	}

	public void setNumeroCniInfirmier(int numeroCniInfirmier) {
		this.numeroCniInfirmier = numeroCniInfirmier;
	}

	@Column(name = "photo_infirmier", length = 45)
	public String getPhotoInfirmier() {
		return this.photoInfirmier;
	}

	public void setPhotoInfirmier(String photoInfirmier) {
		this.photoInfirmier = photoInfirmier;
	}

	@Column(name = "salaire_Infirmier", precision = 22, scale = 0)
	public Double getSalaireInfirmier() {
		return this.salaireInfirmier;
	}

	public void setSalaireInfirmier(Double salaireInfirmier) {
		this.salaireInfirmier = salaireInfirmier;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "infirmier")
	public Set<Examen> getExamens() {
		return this.examens;
	}

	public void setExamens(Set<Examen> examens) {
		this.examens = examens;
	}

}
