package  com.cemedo.data;
// Generated 1 juin 2022 � 14:01:29 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Informaticien generated by hbm2java
 */
@Entity
@Table(name = "informaticien", catalog = "heroku_88ae11bd39df693")
public class Informaticien implements java.io.Serializable {

	private Integer idInformaticiens;
	private String nomInformaticiens;
	private String prenomInformaticiens;
	private String genreInformaticiens;
	private String residenceInformaticiens;
	private int numeroCniInformaticiens;
	private String emailInformaticiens;
	private String telephoneInformaticiens;
	private String passwordInformaticiens;
	private String photoInformaticiens;
	private String fonctionInformaticiens;

	public Informaticien() {
	}

	public Informaticien(String nomInformaticiens, String prenomInformaticiens, String genreInformaticiens,
			String residenceInformaticiens, int numeroCniInformaticiens, String emailInformaticiens,
			String telephoneInformaticiens, String passwordInformaticiens) {
		this.nomInformaticiens = nomInformaticiens;
		this.prenomInformaticiens = prenomInformaticiens;
		this.genreInformaticiens = genreInformaticiens;
		this.residenceInformaticiens = residenceInformaticiens;
		this.numeroCniInformaticiens = numeroCniInformaticiens;
		this.emailInformaticiens = emailInformaticiens;
		this.telephoneInformaticiens = telephoneInformaticiens;
		this.passwordInformaticiens = passwordInformaticiens;
	}

	public Informaticien(String nomInformaticiens, String prenomInformaticiens, String genreInformaticiens,
			String residenceInformaticiens, int numeroCniInformaticiens, String emailInformaticiens,
			String telephoneInformaticiens, String passwordInformaticiens, String photoInformaticiens,
			String fonctionInformaticiens) {
		this.nomInformaticiens = nomInformaticiens;
		this.prenomInformaticiens = prenomInformaticiens;
		this.genreInformaticiens = genreInformaticiens;
		this.residenceInformaticiens = residenceInformaticiens;
		this.numeroCniInformaticiens = numeroCniInformaticiens;
		this.emailInformaticiens = emailInformaticiens;
		this.telephoneInformaticiens = telephoneInformaticiens;
		this.passwordInformaticiens = passwordInformaticiens;
		this.photoInformaticiens = photoInformaticiens;
		this.fonctionInformaticiens = fonctionInformaticiens;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_informaticiens", unique = true, nullable = false)
	public Integer getIdInformaticiens() {
		return this.idInformaticiens;
	}

	public void setIdInformaticiens(Integer idInformaticiens) {
		this.idInformaticiens = idInformaticiens;
	}

	@Column(name = "nom_informaticiens", nullable = false, length = 45)
	public String getNomInformaticiens() {
		return this.nomInformaticiens;
	}

	public void setNomInformaticiens(String nomInformaticiens) {
		this.nomInformaticiens = nomInformaticiens;
	}

	@Column(name = "prenom_informaticiens", nullable = false, length = 45)
	public String getPrenomInformaticiens() {
		return this.prenomInformaticiens;
	}

	public void setPrenomInformaticiens(String prenomInformaticiens) {
		this.prenomInformaticiens = prenomInformaticiens;
	}

	@Column(name = "genre_informaticiens", nullable = false, length = 45)
	public String getGenreInformaticiens() {
		return this.genreInformaticiens;
	}

	public void setGenreInformaticiens(String genreInformaticiens) {
		this.genreInformaticiens = genreInformaticiens;
	}

	@Column(name = "residence_informaticiens", nullable = false, length = 45)
	public String getResidenceInformaticiens() {
		return this.residenceInformaticiens;
	}

	public void setResidenceInformaticiens(String residenceInformaticiens) {
		this.residenceInformaticiens = residenceInformaticiens;
	}

	@Column(name = "numero_CNI_informaticiens", nullable = false)
	public int getNumeroCniInformaticiens() {
		return this.numeroCniInformaticiens;
	}

	public void setNumeroCniInformaticiens(int numeroCniInformaticiens) {
		this.numeroCniInformaticiens = numeroCniInformaticiens;
	}

	@Column(name = "email_informaticiens", nullable = false, length = 45)
	public String getEmailInformaticiens() {
		return this.emailInformaticiens;
	}

	public void setEmailInformaticiens(String emailInformaticiens) {
		this.emailInformaticiens = emailInformaticiens;
	}

	@Column(name = "telephone_informaticiens", nullable = false, length = 45)
	public String getTelephoneInformaticiens() {
		return this.telephoneInformaticiens;
	}

	public void setTelephoneInformaticiens(String telephoneInformaticiens) {
		this.telephoneInformaticiens = telephoneInformaticiens;
	}

	@Column(name = "password_informaticiens", nullable = false, length = 45)
	public String getPasswordInformaticiens() {
		return this.passwordInformaticiens;
	}

	public void setPasswordInformaticiens(String passwordInformaticiens) {
		this.passwordInformaticiens = passwordInformaticiens;
	}

	@Column(name = "photo_informaticiens", length = 45)
	public String getPhotoInformaticiens() {
		return this.photoInformaticiens;
	}

	public void setPhotoInformaticiens(String photoInformaticiens) {
		this.photoInformaticiens = photoInformaticiens;
	}

	@Column(name = "fonction_informaticiens", length = 45)
	public String getFonctionInformaticiens() {
		return this.fonctionInformaticiens;
	}

	public void setFonctionInformaticiens(String fonctionInformaticiens) {
		this.fonctionInformaticiens = fonctionInformaticiens;
	}

}
