package  com.cemedo.data;
// Generated 1 juin 2022 � 14:01:29 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Livraison generated by hbm2java
 */
@Entity
@Table(name = "livraison", catalog = "heroku_88ae11bd39df693")
public class Livraison implements java.io.Serializable {

	private Integer idLivraisons;
	private Patient patient;
	private String modePaiement;

	public Livraison() {
	}

	public Livraison(Patient patient, String modePaiement) {
		this.patient = patient;
		this.modePaiement = modePaiement;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_Livraisons", unique = true, nullable = false)
	public Integer getIdLivraisons() {
		return this.idLivraisons;
	}

	public void setIdLivraisons(Integer idLivraisons) {
		this.idLivraisons = idLivraisons;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Patients_id_Patients", nullable = false)
	public Patient getPatient() {
		return this.patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	@Column(name = "mode_paiement", nullable = false, length = 45)
	public String getModePaiement() {
		return this.modePaiement;
	}

	public void setModePaiement(String modePaiement) {
		this.modePaiement = modePaiement;
	}

}
