package  com.cemedo.data;
// Generated 1 juin 2022 � 14:01:29 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Medicament generated by hbm2java
 */
@Entity
@Table(name = "medicament", catalog = "heroku_88ae11bd39df693")
public class Medicament implements java.io.Serializable {

	private Integer idMedicament;
	private Pharmacien pharmacien;
	private String nomMedicament;
	private int quantiteMedicament;
	private double prixMedicament;
	private String posologieMedicament;
	private String descriptionMedicament;
	private Date dateAchat;
	private Date dateDePeremption;

	public Medicament() {
	}

	public Medicament(Pharmacien pharmacien, String nomMedicament, int quantiteMedicament, double prixMedicament,
			String posologieMedicament, Date dateAchat, Date dateDePeremption) {
		this.pharmacien = pharmacien;
		this.nomMedicament = nomMedicament;
		this.quantiteMedicament = quantiteMedicament;
		this.prixMedicament = prixMedicament;
		this.posologieMedicament = posologieMedicament;
		this.dateAchat = dateAchat;
		this.dateDePeremption = dateDePeremption;
	}

	public Medicament(Pharmacien pharmacien, String nomMedicament, int quantiteMedicament, double prixMedicament,
			String posologieMedicament, String descriptionMedicament, Date dateAchat, Date dateDePeremption) {
		this.pharmacien = pharmacien;
		this.nomMedicament = nomMedicament;
		this.quantiteMedicament = quantiteMedicament;
		this.prixMedicament = prixMedicament;
		this.posologieMedicament = posologieMedicament;
		this.descriptionMedicament = descriptionMedicament;
		this.dateAchat = dateAchat;
		this.dateDePeremption = dateDePeremption;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_Medicament", unique = true, nullable = false)
	public Integer getIdMedicament() {
		return this.idMedicament;
	}

	public void setIdMedicament(Integer idMedicament) {
		this.idMedicament = idMedicament;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Pharmaciens_id_pharmacien", nullable = false)
	public Pharmacien getPharmacien() {
		return this.pharmacien;
	}

	public void setPharmacien(Pharmacien pharmacien) {
		this.pharmacien = pharmacien;
	}

	@Column(name = "nom_Medicament", nullable = false, length = 45)
	public String getNomMedicament() {
		return this.nomMedicament;
	}

	public void setNomMedicament(String nomMedicament) {
		this.nomMedicament = nomMedicament;
	}

	@Column(name = "quantite_Medicament", nullable = false)
	public int getQuantiteMedicament() {
		return this.quantiteMedicament;
	}

	public void setQuantiteMedicament(int quantiteMedicament) {
		this.quantiteMedicament = quantiteMedicament;
	}

	@Column(name = "prix_Medicament", nullable = false, precision = 22, scale = 0)
	public double getPrixMedicament() {
		return this.prixMedicament;
	}

	public void setPrixMedicament(double prixMedicament) {
		this.prixMedicament = prixMedicament;
	}

	@Column(name = "posologie_Medicament", nullable = false, length = 45)
	public String getPosologieMedicament() {
		return this.posologieMedicament;
	}

	public void setPosologieMedicament(String posologieMedicament) {
		this.posologieMedicament = posologieMedicament;
	}

	@Column(name = "description_Medicament", length = 45)
	public String getDescriptionMedicament() {
		return this.descriptionMedicament;
	}

	public void setDescriptionMedicament(String descriptionMedicament) {
		this.descriptionMedicament = descriptionMedicament;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_achat", nullable = false, length = 10)
	public Date getDateAchat() {
		return this.dateAchat;
	}

	public void setDateAchat(Date dateAchat) {
		this.dateAchat = dateAchat;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_de_peremption", nullable = false, length = 10)
	public Date getDateDePeremption() {
		return this.dateDePeremption;
	}

	public void setDateDePeremption(Date dateDePeremption) {
		this.dateDePeremption = dateDePeremption;
	}

}
