package  com.cemedo.data;
// Generated 1 juin 2022 � 14:01:29 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ordonnance generated by hbm2java
 */
@Entity
@Table(name = "ordonnance", catalog = "heroku_88ae11bd39df693")
public class Ordonnance implements java.io.Serializable {

	private int idOrdonnance;
	private Medecin medecin;
	private Patient patient;
	private Pharmacien pharmacien;
	private double montantOrdonnance;
	private String posologieOrdonnance;
	private String descriptionOrdonnance;
	private String dateOrdonnance;
	private String tempDeTraitement;
	private Set<Examen> examens = new HashSet<Examen>(0);
	private Set<Medicament2> medicament2s = new HashSet<Medicament2>(0);

	public Ordonnance() {
	}

	public Ordonnance(int id, Medecin medecin, Patient patient, double montantOrdonnance,
			String posologieOrdonnance, String descriptionOrdonnance, String dateOrdonnance, String tempDeTraitement) {
		this.idOrdonnance = id;
		this.medecin = medecin;
		this.patient = patient;
		this.montantOrdonnance = montantOrdonnance;
		this.posologieOrdonnance = posologieOrdonnance;
		this.descriptionOrdonnance = descriptionOrdonnance;
		this.dateOrdonnance = dateOrdonnance;
		this.tempDeTraitement = tempDeTraitement;
	}

	public Ordonnance(int id, Medecin medecin, Patient patient, Pharmacien pharmacien,
			double montantOrdonnance, String posologieOrdonnance, String descriptionOrdonnance, String dateOrdonnance,
			String tempDeTraitement, Set<Examen> examens, Set<Medicament2> medicament2s) {
		this.idOrdonnance = id;
		this.medecin = medecin;
		this.patient = patient;
		this.pharmacien = pharmacien;
		this.montantOrdonnance = montantOrdonnance;
		this.posologieOrdonnance = posologieOrdonnance;
		this.descriptionOrdonnance = descriptionOrdonnance;
		this.dateOrdonnance = dateOrdonnance;
		this.tempDeTraitement = tempDeTraitement;
		this.examens = examens;
		this.medicament2s = medicament2s;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_ordonnance", unique = true, nullable = false)
	public int getIdOrdonnance() {
		return idOrdonnance;
	}

	public void setIdOrdonnance(int idOrdonnance) {
		this.idOrdonnance = idOrdonnance;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Medecins_id_Medecins", nullable = false)
	public Medecin getMedecin() {
		return this.medecin;
	}

	public void setMedecin(Medecin medecin) {
		this.medecin = medecin;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Patients_id_Patients", nullable = false, insertable = false, updatable = false)
	public Patient getPatient() {
		return this.patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Pharmaciens_id_pharmacien")
	public Pharmacien getPharmacien() {
		return this.pharmacien;
	}

	public void setPharmacien(Pharmacien pharmacien) {
		this.pharmacien = pharmacien;
	}

	@Column(name = "montant_ordonnance", nullable = false, precision = 22, scale = 0)
	public double getMontantOrdonnance() {
		return this.montantOrdonnance;
	}

	public void setMontantOrdonnance(double montantOrdonnance) {
		this.montantOrdonnance = montantOrdonnance;
	}

	@Column(name = "posologie_ordonnance", nullable = false, length = 45)
	public String getPosologieOrdonnance() {
		return this.posologieOrdonnance;
	}

	public void setPosologieOrdonnance(String posologieOrdonnance) {
		this.posologieOrdonnance = posologieOrdonnance;
	}

	@Column(name = "description_ordonnance", nullable = false, length = 45)
	public String getDescriptionOrdonnance() {
		return this.descriptionOrdonnance;
	}

	public void setDescriptionOrdonnance(String descriptionOrdonnance) {
		this.descriptionOrdonnance = descriptionOrdonnance;
	}

	@Column(name = "date_ordonnance", nullable = false, length = 45)
	public String getDateOrdonnance() {
		return this.dateOrdonnance;
	}

	public void setDateOrdonnance(String dateOrdonnance) {
		this.dateOrdonnance = dateOrdonnance;
	}

	@Column(name = "temp_de_traitement", nullable = false, length = 50)
	public String getTempDeTraitement() {
		return this.tempDeTraitement;
	}

	public void setTempDeTraitement(String tempDeTraitement) {
		this.tempDeTraitement = tempDeTraitement;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "ordonnances_has_examens", catalog = "heroku_88ae11bd39df693", joinColumns = {
			@JoinColumn(name = "Ordonnances_id_ordonnance", nullable = false, updatable = false)},
	        inverseJoinColumns = {
					             @JoinColumn(name = "Examens_id_examen", nullable = false, updatable = false) })
	public Set<Examen> getExamens() {
		return this.examens;
	}

	public void setExamens(Set<Examen> examens) {
		this.examens = examens;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "medicaments_has_ordonnances", catalog = "heroku_88ae11bd39df693", joinColumns = {
			@JoinColumn(name = "Ordonnances_id_ordonnance", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "Medicaments_id_medicament", nullable = false, updatable = false)})
	public Set<Medicament2> getMedicament2s() {
		return this.medicament2s;
	}

	public void setMedicament2s(Set<Medicament2> medicament2s) {
		this.medicament2s = medicament2s;
	}

}
