package  com.cemedo.data;
// Generated 1 juin 2022 � 14:01:29 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OrdonnanceId generated by hbm2java
 */
@Embeddable
public class OrdonnanceId implements java.io.Serializable {

	private int idOrdonnance;
	private int patientsIdPatients;

	public OrdonnanceId() {
	}

	public OrdonnanceId(int idOrdonnance, int patientsIdPatients) {
		this.idOrdonnance = idOrdonnance;
		this.patientsIdPatients = patientsIdPatients;
	}

	@Column(name = "id_ordonnance", nullable = false)
	public int getIdOrdonnance() {
		return this.idOrdonnance;
	}

	public void setIdOrdonnance(int idOrdonnance) {
		this.idOrdonnance = idOrdonnance;
	}

	@Column(name = "Patients_id_Patients", nullable = false)
	public int getPatientsIdPatients() {
		return this.patientsIdPatients;
	}

	public void setPatientsIdPatients(int patientsIdPatients) {
		this.patientsIdPatients = patientsIdPatients;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrdonnanceId))
			return false;
		OrdonnanceId castOther = (OrdonnanceId) other;

		return (this.getIdOrdonnance() == castOther.getIdOrdonnance())
				&& (this.getPatientsIdPatients() == castOther.getPatientsIdPatients());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdOrdonnance();
		result = 37 * result + this.getPatientsIdPatients();
		return result;
	}

}
