package  com.cemedo.data;
// Generated 1 juin 2022 � 14:01:29 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pharmacien generated by hbm2java
 */
@Entity
@Table(name = "pharmacien", catalog = "heroku_88ae11bd39df693")
public class Pharmacien implements java.io.Serializable {

	private Integer idPharmacien;
	private String nomPharmacien;
	private String prenomPharmacien;
	private String genrePharmacien;
	private String residencePharmacien;
	private String emailPharmacien;
	private int telephoneHarmacien;
	private String passwordPharmacien;
	private int numeroCniPharmacien;
	private String photoPharmacien;
	private Double salairePharmacien;
	private Double primePharmacien;
	private Set<Medicament> medicaments = new HashSet<Medicament>(0);
	private Set<Ordonnance> ordonnances = new HashSet<Ordonnance>(0);

	public Pharmacien() {
	}

	public Pharmacien(String nomPharmacien, String prenomPharmacien, String genrePharmacien, String residencePharmacien,
			String emailPharmacien, int telephoneHarmacien, String passwordPharmacien, int numeroCniPharmacien) {
		this.nomPharmacien = nomPharmacien;
		this.prenomPharmacien = prenomPharmacien;
		this.genrePharmacien = genrePharmacien;
		this.residencePharmacien = residencePharmacien;
		this.emailPharmacien = emailPharmacien;
		this.telephoneHarmacien = telephoneHarmacien;
		this.passwordPharmacien = passwordPharmacien;
		this.numeroCniPharmacien = numeroCniPharmacien;
	}

	public Pharmacien(String nomPharmacien, String prenomPharmacien, String genrePharmacien, String residencePharmacien,
			String emailPharmacien, int telephoneHarmacien, String passwordPharmacien, int numeroCniPharmacien,
			String photoPharmacien, Double salairePharmacien, Double primePharmacien, Set<Medicament> medicaments,
			Set<Ordonnance> ordonnances) {
		this.nomPharmacien = nomPharmacien;
		this.prenomPharmacien = prenomPharmacien;
		this.genrePharmacien = genrePharmacien;
		this.residencePharmacien = residencePharmacien;
		this.emailPharmacien = emailPharmacien;
		this.telephoneHarmacien = telephoneHarmacien;
		this.passwordPharmacien = passwordPharmacien;
		this.numeroCniPharmacien = numeroCniPharmacien;
		this.photoPharmacien = photoPharmacien;
		this.salairePharmacien = salairePharmacien;
		this.primePharmacien = primePharmacien;
		this.medicaments = medicaments;
		this.ordonnances = ordonnances;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_pharmacien", unique = true, nullable = false)
	public Integer getIdPharmacien() {
		return this.idPharmacien;
	}

	public void setIdPharmacien(Integer idPharmacien) {
		this.idPharmacien = idPharmacien;
	}

	@Column(name = "nom_pharmacien", nullable = false, length = 45)
	public String getNomPharmacien() {
		return this.nomPharmacien;
	}

	public void setNomPharmacien(String nomPharmacien) {
		this.nomPharmacien = nomPharmacien;
	}

	@Column(name = "prenom_pharmacien", nullable = false, length = 45)
	public String getPrenomPharmacien() {
		return this.prenomPharmacien;
	}

	public void setPrenomPharmacien(String prenomPharmacien) {
		this.prenomPharmacien = prenomPharmacien;
	}

	@Column(name = "genre_pharmacien", nullable = false, length = 45)
	public String getGenrePharmacien() {
		return this.genrePharmacien;
	}

	public void setGenrePharmacien(String genrePharmacien) {
		this.genrePharmacien = genrePharmacien;
	}

	@Column(name = "residence_pharmacien", nullable = false, length = 45)
	public String getResidencePharmacien() {
		return this.residencePharmacien;
	}

	public void setResidencePharmacien(String residencePharmacien) {
		this.residencePharmacien = residencePharmacien;
	}

	@Column(name = "email_pharmacien", nullable = false, length = 45)
	public String getEmailPharmacien() {
		return this.emailPharmacien;
	}

	public void setEmailPharmacien(String emailPharmacien) {
		this.emailPharmacien = emailPharmacien;
	}

	@Column(name = "telephone_harmacien", nullable = false)
	public int getTelephoneHarmacien() {
		return this.telephoneHarmacien;
	}

	public void setTelephoneHarmacien(int telephoneHarmacien) {
		this.telephoneHarmacien = telephoneHarmacien;
	}

	@Column(name = "password_pharmacien", nullable = false, length = 45)
	public String getPasswordPharmacien() {
		return this.passwordPharmacien;
	}

	public void setPasswordPharmacien(String passwordPharmacien) {
		this.passwordPharmacien = passwordPharmacien;
	}

	@Column(name = "numero_CNI_pharmacien", nullable = false)
	public int getNumeroCniPharmacien() {
		return this.numeroCniPharmacien;
	}

	public void setNumeroCniPharmacien(int numeroCniPharmacien) {
		this.numeroCniPharmacien = numeroCniPharmacien;
	}

	@Column(name = "Photo_pharmacien", length = 45)
	public String getPhotoPharmacien() {
		return this.photoPharmacien;
	}

	public void setPhotoPharmacien(String photoPharmacien) {
		this.photoPharmacien = photoPharmacien;
	}

	@Column(name = "salaire_pharmacien", precision = 22, scale = 0)
	public Double getSalairePharmacien() {
		return this.salairePharmacien;
	}

	public void setSalairePharmacien(Double salairePharmacien) {
		this.salairePharmacien = salairePharmacien;
	}

	@Column(name = "prime_pharmacien", precision = 22, scale = 0)
	public Double getPrimePharmacien() {
		return this.primePharmacien;
	}

	public void setPrimePharmacien(Double primePharmacien) {
		this.primePharmacien = primePharmacien;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pharmacien")
	public Set<Medicament> getMedicaments() {
		return this.medicaments;
	}

	public void setMedicaments(Set<Medicament> medicaments) {
		this.medicaments = medicaments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pharmacien")
	public Set<Ordonnance> getOrdonnances() {
		return this.ordonnances;
	}

	public void setOrdonnances(Set<Ordonnance> ordonnances) {
		this.ordonnances = ordonnances;
	}

}
