package  com.cemedo.data;
// Generated 1 juin 2022 � 14:01:29 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Rapport generated by hbm2java
 */
@Entity
@Table(name = "rapport", catalog = "heroku_88ae11bd39df693")
public class Rapport implements java.io.Serializable {

	private Integer idRapport;
	private Medecin medecin;
	private Patient patient;
	private Date debutDeTraitement;
	private Date finDeTraitement;
	private String etatDeSante;
	private String typeRapport;

	public Rapport() {
	}

	public Rapport(Medecin medecin, Patient patient, Date debutDeTraitement, Date finDeTraitement, String etatDeSante,
			String typeRapport) {
		this.medecin = medecin;
		this.patient = patient;
		this.debutDeTraitement = debutDeTraitement;
		this.finDeTraitement = finDeTraitement;
		this.etatDeSante = etatDeSante;
		this.typeRapport = typeRapport;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_Rapport", unique = true, nullable = false)
	public Integer getIdRapport() {
		return this.idRapport;
	}

	public void setIdRapport(Integer idRapport) {
		this.idRapport = idRapport;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Medecins_id_Medecins", nullable = false)
	public Medecin getMedecin() {
		return this.medecin;
	}

	public void setMedecin(Medecin medecin) {
		this.medecin = medecin;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Patients_id_Patients", nullable = false)
	public Patient getPatient() {
		return this.patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Debut_de_traitement", nullable = false, length = 10)
	public Date getDebutDeTraitement() {
		return this.debutDeTraitement;
	}

	public void setDebutDeTraitement(Date debutDeTraitement) {
		this.debutDeTraitement = debutDeTraitement;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Fin_de_traitement", nullable = false, length = 10)
	public Date getFinDeTraitement() {
		return this.finDeTraitement;
	}

	public void setFinDeTraitement(Date finDeTraitement) {
		this.finDeTraitement = finDeTraitement;
	}

	@Column(name = "Etat_de_sante", nullable = false, length = 45)
	public String getEtatDeSante() {
		return this.etatDeSante;
	}

	public void setEtatDeSante(String etatDeSante) {
		this.etatDeSante = etatDeSante;
	}

	@Column(name = "type_Rapport", nullable = false, length = 45)
	public String getTypeRapport() {
		return this.typeRapport;
	}

	public void setTypeRapport(String typeRapport) {
		this.typeRapport = typeRapport;
	}

}
