package  com.cemedo.data;
// Generated 1 juin 2022 � 14:01:29 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reception generated by hbm2java
 */
@Entity
@Table(name = "reception", catalog = "heroku_88ae11bd39df693")
public class Reception implements java.io.Serializable {

	private Integer idReception;
	private String nomReception;
	private String prenomReception;
	private String genreReception;
	private String residenceReception;
	private String emailReception;
	private int telephoneReception;
	private String passwordReception;
	private int numeroCniReception;
	private String photoReception;
	private Double salaireReception;
	private Date dateNaissanceReception;
	private Set<Rendezvous> rendezvouses = new HashSet<Rendezvous>(0);
	private Set<Appl> appls = new HashSet<Appl>(0);
	private Set<Chat> chats = new HashSet<Chat>(0);

	public Reception() {
	}

	public Reception(String nomReception, String prenomReception, String genreReception, String residenceReception,
			String emailReception, int telephoneReception, String passwordReception, int numeroCniReception,
			Date dateNaissanceReception) {
		this.nomReception = nomReception;
		this.prenomReception = prenomReception;
		this.genreReception = genreReception;
		this.residenceReception = residenceReception;
		this.emailReception = emailReception;
		this.telephoneReception = telephoneReception;
		this.passwordReception = passwordReception;
		this.numeroCniReception = numeroCniReception;
		this.dateNaissanceReception = dateNaissanceReception;
	}

	public Reception(String nomReception, String prenomReception, String genreReception, String residenceReception,
			String emailReception, int telephoneReception, String passwordReception, int numeroCniReception,
			String photoReception, Double salaireReception, Date dateNaissanceReception, Set<Rendezvous> rendezvouses,
			Set<Appl> appls, Set<Chat> chats) {
		this.nomReception = nomReception;
		this.prenomReception = prenomReception;
		this.genreReception = genreReception;
		this.residenceReception = residenceReception;
		this.emailReception = emailReception;
		this.telephoneReception = telephoneReception;
		this.passwordReception = passwordReception;
		this.numeroCniReception = numeroCniReception;
		this.photoReception = photoReception;
		this.salaireReception = salaireReception;
		this.dateNaissanceReception = dateNaissanceReception;
		this.rendezvouses = rendezvouses;
		this.appls = appls;
		this.chats = chats;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_reception", unique = true, nullable = false)
	public Integer getIdReception() {
		return this.idReception;
	}

	public void setIdReception(Integer idReception) {
		this.idReception = idReception;
	}

	@Column(name = "nom_reception", nullable = false, length = 45)
	public String getNomReception() {
		return this.nomReception;
	}

	public void setNomReception(String nomReception) {
		this.nomReception = nomReception;
	}

	@Column(name = "prenom_reception", nullable = false, length = 45)
	public String getPrenomReception() {
		return this.prenomReception;
	}

	public void setPrenomReception(String prenomReception) {
		this.prenomReception = prenomReception;
	}

	@Column(name = "genre_reception", nullable = false, length = 45)
	public String getGenreReception() {
		return this.genreReception;
	}

	public void setGenreReception(String genreReception) {
		this.genreReception = genreReception;
	}

	@Column(name = "residence_reception", nullable = false, length = 45)
	public String getResidenceReception() {
		return this.residenceReception;
	}

	public void setResidenceReception(String residenceReception) {
		this.residenceReception = residenceReception;
	}

	@Column(name = "email_reception", nullable = false, length = 45)
	public String getEmailReception() {
		return this.emailReception;
	}

	public void setEmailReception(String emailReception) {
		this.emailReception = emailReception;
	}

	@Column(name = "telephone_reception", nullable = false)
	public int getTelephoneReception() {
		return this.telephoneReception;
	}

	public void setTelephoneReception(int telephoneReception) {
		this.telephoneReception = telephoneReception;
	}

	@Column(name = "password_reception", nullable = false, length = 45)
	public String getPasswordReception() {
		return this.passwordReception;
	}

	public void setPasswordReception(String passwordReception) {
		this.passwordReception = passwordReception;
	}

	@Column(name = "numero_CNI_reception", nullable = false)
	public int getNumeroCniReception() {
		return this.numeroCniReception;
	}

	public void setNumeroCniReception(int numeroCniReception) {
		this.numeroCniReception = numeroCniReception;
	}

	@Column(name = "photo_reception", length = 45)
	public String getPhotoReception() {
		return this.photoReception;
	}

	public void setPhotoReception(String photoReception) {
		this.photoReception = photoReception;
	}

	@Column(name = "salaire_reception", precision = 22, scale = 0)
	public Double getSalaireReception() {
		return this.salaireReception;
	}

	public void setSalaireReception(Double salaireReception) {
		this.salaireReception = salaireReception;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_naissance_reception", nullable = false, length = 26)
	public Date getDateNaissanceReception() {
		return this.dateNaissanceReception;
	}

	public void setDateNaissanceReception(Date dateNaissanceReception) {
		this.dateNaissanceReception = dateNaissanceReception;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reception")
	public Set<Rendezvous> getRendezvouses() {
		return this.rendezvouses;
	}

	public void setRendezvouses(Set<Rendezvous> rendezvouses) {
		this.rendezvouses = rendezvouses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reception")
	public Set<Appl> getAppls() {
		return this.appls;
	}

	public void setAppls(Set<Appl> appls) {
		this.appls = appls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reception")
	public Set<Chat> getChats() {
		return this.chats;
	}

	public void setChats(Set<Chat> chats) {
		this.chats = chats;
	}

}
