package Base_Donnee;
// Generated 21 mars 2022 à 18:17:48 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Avoir generated by hbm2java
 */
@Entity
@Table(name = "avoir", catalog = "heroku_88ae11bd39df693")
public class Avoir implements java.io.Serializable {

	private AvoirId id;

	public Avoir() {
	}

	public Avoir(AvoirId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idService", column = @Column(name = "id_Service", nullable = false)),
			@AttributeOverride(name = "idChambre", column = @Column(name = "id_Chambre", nullable = false)) })
	public AvoirId getId() {
		return this.id;
	}

	public void setId(AvoirId id) {
		this.id = id;
	}

}
