package Base_Donnee;
// Generated 21 mars 2022 à 18:17:48 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AvoirId generated by hbm2java
 */
@Embeddable
public class AvoirId implements java.io.Serializable {

	private int idService;
	private int idChambre;

	public AvoirId() {
	}

	public AvoirId(int idService, int idChambre) {
		this.idService = idService;
		this.idChambre = idChambre;
	}

	@Column(name = "id_Service", nullable = false)
	public int getIdService() {
		return this.idService;
	}

	public void setIdService(int idService) {
		this.idService = idService;
	}

	@Column(name = "id_Chambre", nullable = false)
	public int getIdChambre() {
		return this.idChambre;
	}

	public void setIdChambre(int idChambre) {
		this.idChambre = idChambre;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AvoirId))
			return false;
		AvoirId castOther = (AvoirId) other;

		return (this.getIdService() == castOther.getIdService()) && (this.getIdChambre() == castOther.getIdChambre());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdService();
		result = 37 * result + this.getIdChambre();
		return result;
	}

}
