package Base_Donnee;
// Generated 4 mars 2022 à 18:08:38 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Chambres generated by hbm2java
 */
//heroku_88ae11bd39df693
@Entity
@Table(name = "chambres", catalog = "heroku_88ae11bd39df693")
public class Chambres implements java.io.Serializable {

	private int chambreNumero;
	private int chambreTelephone;
	private String chambreDescription;
	private double chambrePrix;
	private Set<Reservations> reservationses = new HashSet<Reservations>(0);
	private Set<Occupation> occupations = new HashSet<Occupation>(0);
	private Set<Services> serviceses = new HashSet<Services>(0);

	public Chambres() {
	}

	public Chambres(int chambreNumero, int chambreTelephone, String chambreDescription, double chambrePrix) {
		this.chambreNumero = chambreNumero;
		this.chambreTelephone = chambreTelephone;
		this.chambreDescription = chambreDescription;
		this.chambrePrix = chambrePrix;
	}

	public Chambres(int chambreNumero, int chambreTelephone, String chambreDescription, double chambrePrix,
			Set<Reservations> reservationses, Set<Occupation> occupations, Set<Services> serviceses) {
		this.chambreNumero = chambreNumero;
		this.chambreTelephone = chambreTelephone;
		this.chambreDescription = chambreDescription;
		this.chambrePrix = chambrePrix;
		this.reservationses = reservationses;
		this.occupations = occupations;
		this.serviceses = serviceses;
	}

	@Id

	@Column(name = "Chambre_Numero", unique = true, nullable = false)
	public int getChambreNumero() {
		return this.chambreNumero;
	}

	public void setChambreNumero(int chambreNumero) {
		this.chambreNumero = chambreNumero;
	}

	@Column(name = "Chambre_Telephone", nullable = false)
	public int getChambreTelephone() {
		return this.chambreTelephone;
	}

	public void setChambreTelephone(int chambreTelephone) {
		this.chambreTelephone = chambreTelephone;
	}

	@Column(name = "Chambre_Description", nullable = false, length = 45)
	public String getChambreDescription() {
		return this.chambreDescription;
	}

	public void setChambreDescription(String chambreDescription) {
		this.chambreDescription = chambreDescription;
	}

	@Column(name = "Chambre_Prix", nullable = false, precision = 22, scale = 0)
	public double getChambrePrix() {
		return this.chambrePrix;
	}

	public void setChambrePrix(double chambrePrix) {
		this.chambrePrix = chambrePrix;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "chambres")
	public Set<Reservations> getReservationses() {
		return this.reservationses;
	}

	public void setReservationses(Set<Reservations> reservationses) {
		this.reservationses = reservationses;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "chambres")
	public Set<Occupation> getOccupations() {
		return this.occupations;
	}

	public void setOccupations(Set<Occupation> occupations) {
		this.occupations = occupations;
	}

	@ManyToMany(fetch = FetchType.EAGER)
	@JoinTable(name = "avoir", catalog = "heroku_88ae11bd39df693", joinColumns = {
			@JoinColumn(name = "id_Chambre", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "id_Service", nullable = false, updatable = false) })
	public Set<Services> getServiceses() {
		return this.serviceses;
	}

	public void setServiceses(Set<Services> serviceses) {
		this.serviceses = serviceses;
	}

}
