package Base_Donnee;
// Generated 4 mars 2022 à 18:08:38 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Employes generated by hbm2java
 */
//heroku_88ae11bd39df693
@Entity
@Table(name = "employes", catalog = "heroku_88ae11bd39df693")
public class Employes implements java.io.Serializable {

	private Integer employeId;
	private Services services;
	private String employeNom;
	private String employePrenom;
	private int employeAge;
	private String employeGenre;
	private String employeVille;
	private int employeNumero;

	public Employes() {
	}

	public Employes(Services services, String employeNom, String employePrenom, int employeAge, String employeGenre,
			String employeVille, int employeNumero) {
		this.services = services;
		this.employeNom = employeNom;
		this.employePrenom = employePrenom;
		this.employeAge = employeAge;
		this.employeGenre = employeGenre;
		this.employeVille = employeVille;
		this.employeNumero = employeNumero;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Employe_id", unique = true, nullable = false)
	public Integer getEmployeId() {
		return this.employeId;
	}

	public void setEmployeId(Integer employeId) {
		this.employeId = employeId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Employe_service", nullable = false)
	public Services getServices() {
		return this.services;
	}

	public void setServices(Services services) {
		this.services = services;
	}

	@Column(name = "Employe_Nom", nullable = false, length = 30)
	public String getEmployeNom() {
		return this.employeNom;
	}

	public void setEmployeNom(String employeNom) {
		this.employeNom = employeNom;
	}

	@Column(name = "Employe_Prenom", nullable = false, length = 45)
	public String getEmployePrenom() {
		return this.employePrenom;
	}

	public void setEmployePrenom(String employePrenom) {
		this.employePrenom = employePrenom;
	}

	@Column(name = "Employe_age", nullable = false)
	public int getEmployeAge() {
		return this.employeAge;
	}

	public void setEmployeAge(int employeAge) {
		this.employeAge = employeAge;
	}

	@Column(name = "Employe_Genre", nullable = false, length = 20)
	public String getEmployeGenre() {
		return this.employeGenre;
	}

	public void setEmployeGenre(String employeGenre) {
		this.employeGenre = employeGenre;
	}

	@Column(name = "Employe_Ville", nullable = false, length = 45)
	public String getEmployeVille() {
		return this.employeVille;
	}

	public void setEmployeVille(String employeVille) {
		this.employeVille = employeVille;
	}

	@Column(name = "Employe_Numero", nullable = false)
	public int getEmployeNumero() {
		return this.employeNumero;
	}

	public void setEmployeNumero(int employeNumero) {
		this.employeNumero = employeNumero;
	}

}
