package Base_Donnee;
// Generated 4 mars 2022 à 18:08:38 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Factures generated by hbm2java
 */
//heroku_88ae11bd39df693
@Entity
@Table(name = "factures", catalog = "heroku_88ae11bd39df693")
public class Factures implements java.io.Serializable {

	private Integer factureId;
	private Reservations reservations;
	private double factureMontant;
	private Date factureDate;

	public Factures() {
	}

	public Factures(Reservations reservations, double factureMontant, Date factureDate) {
		this.reservations = reservations;
		this.factureMontant = factureMontant;
		this.factureDate = factureDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Facture_Id", unique = true, nullable = false)
	public Integer getFactureId() {
		return this.factureId;
	}

	public void setFactureId(Integer factureId) {
		this.factureId = factureId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Facture_Reservation", nullable = false)
	public Reservations getReservations() {
		return this.reservations;
	}

	public void setReservations(Reservations reservations) {
		this.reservations = reservations;
	}

	@Column(name = "Facture_Montant", nullable = false, precision = 22, scale = 0)
	public double getFactureMontant() {
		return this.factureMontant;
	}

	public void setFactureMontant(double factureMontant) {
		this.factureMontant = factureMontant;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Facture_Date", nullable = false, length = 10)
	public Date getFactureDate() {
		return this.factureDate;
	}

	public void setFactureDate(Date factureDate) {
		this.factureDate = factureDate;
	}

}
