package Base_Donnee;
// Generated 4 mars 2022 à 18:08:38 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Occupation generated by hbm2java
 */
//heroku_88ae11bd39df693
@Entity
@Table(name = "occupation", catalog = "heroku_88ae11bd39df693")
public class Occupation implements java.io.Serializable {

	private Integer occupationId;
	private Chambres chambres;
	private Clients clients;
	private Date occupationDateDebut;
	private Date occupationDateFin;

	public Occupation() {
	}

	public Occupation(Chambres chambres, Clients clients, Date occupationDateDebut, Date occupationDateFin) {
		this.chambres = chambres;
		this.clients = clients;
		this.occupationDateDebut = occupationDateDebut;
		this.occupationDateFin = occupationDateFin;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Occupation_Id", unique = true, nullable = false)
	public Integer getOccupationId() {
		return this.occupationId;
	}

	public void setOccupationId(Integer occupationId) {
		this.occupationId = occupationId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Occupation_Chambre", nullable = false)
	public Chambres getChambres() {
		return this.chambres;
	}

	public void setChambres(Chambres chambres) {
		this.chambres = chambres;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Occupation_Client", nullable = false)
	public Clients getClients() {
		return this.clients;
	}

	public void setClients(Clients clients) {
		this.clients = clients;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Occupation_Date_Debut", nullable = false, length = 10)
	public Date getOccupationDateDebut() {
		return this.occupationDateDebut;
	}

	public void setOccupationDateDebut(Date occupationDateDebut) {
		this.occupationDateDebut = occupationDateDebut;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Occupation_Date_Fin", nullable = false, length = 10)
	public Date getOccupationDateFin() {
		return this.occupationDateFin;
	}

	public void setOccupationDateFin(Date occupationDateFin) {
		this.occupationDateFin = occupationDateFin;
	}

}
