package Base_Donnee;
// Generated 4 mars 2022 à 18:08:38 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reservations generated by hbm2java
 */
//heroku_88ae11bd39df693
@Entity
@Table(name = "reservations", catalog = "heroku_88ae11bd39df693")
public class Reservations implements java.io.Serializable {

	private Integer reservationId;
	private Chambres chambres;
	private Clients clients;
	private Services services;
	private Date reservationDateDebut;
	private Date reservationDateFin;
	private Date reservationDatePaye;
	private Set<Factures> factureses = new HashSet<Factures>(0);

	public Reservations() {
	}

	public Reservations(Chambres chambres, Clients clients, Services services, Date reservationDateDebut,
			Date reservationDateFin, Date reservationDatePaye) {
		this.chambres = chambres;
		this.clients = clients;
		this.services = services;
		this.reservationDateDebut = reservationDateDebut;
		this.reservationDateFin = reservationDateFin;
		this.reservationDatePaye = reservationDatePaye;
	}

	public Reservations(Chambres chambres, Clients clients, Services services, Date reservationDateDebut,
			Date reservationDateFin, Date reservationDatePaye, Set<Factures> factureses) {
		this.chambres = chambres;
		this.clients = clients;
		this.services = services;
		this.reservationDateDebut = reservationDateDebut;
		this.reservationDateFin = reservationDateFin;
		this.reservationDatePaye = reservationDatePaye;
		this.factureses = factureses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Reservation_Id", unique = true, nullable = false)
	public Integer getReservationId() {
		return this.reservationId;
	}

	public void setReservationId(Integer reservationId) {
		this.reservationId = reservationId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Reservation_Chambre", nullable = false)
	public Chambres getChambres() {
		return this.chambres;
	}

	public void setChambres(Chambres chambres) {
		this.chambres = chambres;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Reservation_Client", nullable = false)
	public Clients getClients() {
		return this.clients;
	}

	public void setClients(Clients clients) {
		this.clients = clients;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Reservation_Service", nullable = false)
	public Services getServices() {
		return this.services;
	}

	public void setServices(Services services) {
		this.services = services;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Reservation_Date_Debut", nullable = false, length = 10)
	public Date getReservationDateDebut() {
		return this.reservationDateDebut;
	}

	public void setReservationDateDebut(Date reservationDateDebut) {
		this.reservationDateDebut = reservationDateDebut;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Reservation_Date_Fin", nullable = false, length = 10)
	public Date getReservationDateFin() {
		return this.reservationDateFin;
	}

	public void setReservationDateFin(Date reservationDateFin) {
		this.reservationDateFin = reservationDateFin;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Reservation_DatePaye", nullable = false, length = 10)
	public Date getReservationDatePaye() {
		return this.reservationDatePaye;
	}

	public void setReservationDatePaye(Date reservationDatePaye) {
		this.reservationDatePaye = reservationDatePaye;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "reservations")
	public Set<Factures> getFactureses() {
		return this.factureses;
	}

	public void setFactureses(Set<Factures> factureses) {
		this.factureses = factureses;
	}

}
