-- MySQL Script generated by MySQL Workbench
-- Tue Mar 22 00:05:19 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Luxury_Hotel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Luxury_Hotel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Luxury_Hotel` DEFAULT CHARACTER SET utf8 ;
USE `Luxury_Hotel` ;

-- -----------------------------------------------------
-- Table `Luxury_Hotel`.`Services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Luxury_Hotel`.`Services` (
  `Services_Id` INT NOT NULL AUTO_INCREMENT,
  `Service_Description` VARCHAR(45) NOT NULL,
  `Service_Heure_Debut` DATE NOT NULL,
  `Service_Heure_Fin` DATE NOT NULL,
  PRIMARY KEY (`Services_Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Luxury_Hotel`.`Employes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Luxury_Hotel`.`Employes` (
  `Employe_id` INT NOT NULL AUTO_INCREMENT,
  `Employe_Nom` VARCHAR(30) NOT NULL,
  `Employe_Prenom` VARCHAR(45) NOT NULL,
  `Employe_age` INT(20) NOT NULL,
  `Employe_Genre` VARCHAR(20) NOT NULL,
  `Employe_Ville` VARCHAR(45) NOT NULL,
  `Employe_Numero` INT(15) NOT NULL,
  `Employe_service` INT NOT NULL,
  PRIMARY KEY (`Employe_id`),
  INDEX `Employe_Service_idx` (`Employe_service` ASC),
  CONSTRAINT `Employe_Service`
    FOREIGN KEY (`Employe_service`)
    REFERENCES `Luxury_Hotel`.`Services` (`Services_Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Luxury_Hotel`.`Clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Luxury_Hotel`.`Clients` (
  `iClient_Id` INT NOT NULL AUTO_INCREMENT,
  `Client_Nom` VARCHAR(30) NOT NULL,
  `Client_Prenom` VARCHAR(30) NOT NULL,
  `Client_age` INT(15) NOT NULL,
  `Client_Numero` INT(20) NOT NULL,
  `Client_Ville` VARCHAR(30) NOT NULL,
  `Client_Profession` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`iClient_Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Luxury_Hotel`.`Chambres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Luxury_Hotel`.`Chambres` (
  `Chambre_Numero` INT NOT NULL,
  `Chambre_Telephone` INT NOT NULL,
  `Chambre_Description` VARCHAR(45) NOT NULL,
  `Chambre_Prix` DOUBLE NOT NULL,
  PRIMARY KEY (`Chambre_Numero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Luxury_Hotel`.`Reservations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Luxury_Hotel`.`Reservations` (
  `Reservation_Id` INT NOT NULL AUTO_INCREMENT,
  `Reservation_Date_Debut` DATE NOT NULL,
  `Reservation_Date_Fin` DATE NOT NULL,
  `Reservation_DatePaye` DATE NOT NULL,
  `Reservation_Service` INT NOT NULL,
  `Reservation_Chambre` INT NOT NULL,
  `Reservation_Client` INT NOT NULL,
  PRIMARY KEY (`Reservation_Id`),
  INDEX `Reservation_Service_idx` (`Reservation_Service` ASC),
  INDEX `Reservation_Chambre_idx` (`Reservation_Chambre` ASC),
  INDEX `Reservation_Client_idx` (`Reservation_Client` ASC),
  CONSTRAINT `Reservation_Service`
    FOREIGN KEY (`Reservation_Service`)
    REFERENCES `Luxury_Hotel`.`Services` (`Services_Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Reservation_Chambre`
    FOREIGN KEY (`Reservation_Chambre`)
    REFERENCES `Luxury_Hotel`.`Chambres` (`Chambre_Numero`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Reservation_Client`
    FOREIGN KEY (`Reservation_Client`)
    REFERENCES `Luxury_Hotel`.`Clients` (`iClient_Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Luxury_Hotel`.`Occupation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Luxury_Hotel`.`Occupation` (
  `Occupation_Id` INT NOT NULL AUTO_INCREMENT,
  `Occupation_Date_Debut` DATE NOT NULL,
  `Occupation_Date_Fin` DATE NOT NULL,
  `Occupation_Chambre` INT NOT NULL,
  `Occupation_Client` INT NOT NULL,
  PRIMARY KEY (`Occupation_Id`),
  INDEX `Occupation_Chambre_idx` (`Occupation_Chambre` ASC),
  INDEX `Occupation_Client_idx` (`Occupation_Client` ASC),
  CONSTRAINT `Occupation_Chambre`
    FOREIGN KEY (`Occupation_Chambre`)
    REFERENCES `Luxury_Hotel`.`Chambres` (`Chambre_Numero`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Occupation_Client`
    FOREIGN KEY (`Occupation_Client`)
    REFERENCES `Luxury_Hotel`.`Clients` (`iClient_Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Luxury_Hotel`.`Factures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Luxury_Hotel`.`Factures` (
  `Facture_Id` INT NOT NULL AUTO_INCREMENT,
  `Facture_Montant` DOUBLE NOT NULL,
  `Facture_Date` DATE NOT NULL,
  `Facture_Reservation` INT NOT NULL,
  PRIMARY KEY (`Facture_Id`),
  INDEX `Facture_Reservation_idx` (`Facture_Reservation` ASC),
  CONSTRAINT `Facture_Reservation`
    FOREIGN KEY (`Facture_Reservation`)
    REFERENCES `Luxury_Hotel`.`Reservations` (`Reservation_Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Luxury_Hotel`.`Avoir`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Luxury_Hotel`.`Avoir` (
  `id_Service` INT NOT NULL,
  `id_Chambre` INT NOT NULL,
  INDEX `id_Service_idx` (`id_Service` ASC),
  INDEX `id_Chambre_idx` (`id_Chambre` ASC),
  PRIMARY KEY (`id_Service`, `id_Chambre`),
  CONSTRAINT `id_Service`
    FOREIGN KEY (`id_Service`)
    REFERENCES `Luxury_Hotel`.`Services` (`Services_Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id_Chambre`
    FOREIGN KEY (`id_Chambre`)
    REFERENCES `Luxury_Hotel`.`Chambres` (`Chambre_Numero`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Luxury_Hotel`.`Authenfication`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Luxury_Hotel`.`Authenfication` (
  `Nom_Utilisateur` VARCHAR(30) NOT NULL,
  `Profession` VARCHAR(45) NOT NULL,
  `Mode_Pwd` VARCHAR(45) NOT NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
